girls_proj/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import (
    ProfileDetailView, ProfileUpdateView, ProfileRedirectView
)


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^redirect/$', ProfileRedirectView.as_view(), name='redirect'),    
    url(r'^(?P<slug>[-\w]+)/$', ProfileDetailView.as_view(), name='profile_detail'),
    url(r'^(?P<slug>[-\w]+)/update/$', ProfileUpdateView.as_view(), name='profile_update'),
]

girls_proj/facemash/urls.py
from django.conf.urls import url

from .views import (
    PlayView, RatingsListView, GirlDetailView, FacemashUpdateView
)


urlpatterns = [
    url(r'^$', PlayView.as_view(), name='play'),
    url(r'^ratings/$', RatingsListView.as_view(), name='ratings'),
    url(r'^update/$', FacemashUpdateView.as_view(), name='update'),
    url(r'^g/(?P<slug>[-\w]+)/$', GirlDetailView.as_view(), name='detail'),
]

girls_proj/landing/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import (
    SearchListView, AboutPage
)


urlpatterns = [
    url(r'^about/$', AboutPage.as_view(), name='about'),
    url(r'^search/$', SearchListView.as_view(), name='search'),
]

girls_proj/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('girls_proj.facemash.urls', namespace='facemash')),
    url(r'^', include('girls_proj.landing.urls', namespace='landing')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^accounts/', include('girls_proj.accounts.urls', namespace='accounts')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]

girls_proj/accounts/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _

from slugify import UniqueSlugify
from imagekit.processors import Adjust, ResizeToFill
from imagekit.models import ProcessedImageField, ImageSpecField
from django_countries.fields import CountryField

from girls_proj.utils.model_utils import UploadToPathAndRename


class Profile(models.Model):
    SEX_CHOICES = (
        (1, _('man')),
        (0, _('woman')),
        (None, _("don't show"))
    )
    user = models.OneToOneField(User, related_name='profile')
    sex = models.IntegerField(choices=SEX_CHOICES, blank=True, null=True, verbose_name=_('gender'))
    slug = models.SlugField(unique=True, max_length=100, help_text=_("automatically generated, don't change manually !"))
    address_line1 = models.CharField(verbose_name=_("address line1"), max_length=200, blank=True, null=True)
    address_line2 = models.CharField(verbose_name=_("address line2"), max_length=200, blank=True, null=True)
    city = models.CharField(_("city"), max_length=200, blank=True, null=True)
    state = CountryField(blank=True, null=True, blank_label=_('(select country)'))
    postal = models.CharField(_("postal"), max_length=200, blank=True, null=True)
    dob = models.DateField(null=True, blank=True, verbose_name=_('birthday'))
    phone = models.CharField(
        max_length=50,
        verbose_name=_("phone"),
        blank=True,
        null=True,
    )
    cell = models.CharField(
        max_length=20,
        verbose_name=_("cell number"),
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex=r'^\+?1?\d{9,15}$',
                message=_("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
            )
        ]
    )
    profile_image = ProcessedImageField(upload_to=UploadToPathAndRename('profile_images'),
                                        processors=[
                                            ResizeToFill(400, 400),
                                            Adjust(sharpness=1.1, contrast=1.1)],
                                        format='JPEG',
                                        options={'quality': 90}, null=True, blank=True)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:profile_detail', kwargs={'slug': self.slug})

    # thumbnail for admin interface
    def admin_image_thumb(self):
        if self.profile_image:
            return '<img src="{0}{1}" width="100" height="100" />'.format(settings.MEDIA_URL, self.profile_image)
        else:
            return '<img src="{0}accounts/default/default-avatar.jpg" width="100" height="100" />'.format(settings.STATIC_URL)
    admin_image_thumb.allow_tags = True

    # small thumbnail and method for it
    profile_image_thumbnail_sm = ImageSpecField(
        source='profile_image',
        processors=[ResizeToFill(155, 155)],
        format='JPEG',
        options={'quality': 80}
    )

    def get_avatar_sm(self):
        if self.profile_image:
            return self.profile_image_thumbnail_sm.url
        else:
            return '{}accounts/default/default-avatar_sm.jpeg'.format(settings.STATIC_URL)

    # extra small thumbnail and method for it
    profile_image_thumbnail_xs = ImageSpecField(
        source='profile_image',
        processors=[ResizeToFill(48, 48)],
        format='JPEG',
        options={'quality': 80}
    )

    def get_avatar_xs(self):
        if self.profile_image:
            return self.profile_image_thumbnail_xs.url
        else:
            return '{}accounts/default/default-avatar_xs.jpeg'.format(settings.STATIC_URL)


def my_unique_check(text, uids):
    if text in uids:
        return False
    return not Profile.objects.filter(slug=text).exists()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        slugify_unique = UniqueSlugify(
            unique_check=my_unique_check,
            separator='_',
            to_lower=True,
            max_length=100
        )
        slug = slugify_unique(instance.username)
        Profile.objects.create(user=instance, slug=slug)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

girls_proj/accounts/forms.py
from django import forms
from django.forms.models import model_to_dict, fields_for_model
from django.contrib.auth.models import User
from django_countries.widgets import CountrySelectWidget
from django.utils.translation import ugettext_lazy as _

from .models import Profile


class ProfileUpdateForm(forms.ModelForm):

    def __init__(self, instance=None, *args, **kwargs):
        _fields = ('first_name', 'last_name',)
        _initial = model_to_dict(instance.user, _fields) if instance is not None else {}
        kwargs.update(initial=_initial)
        super(ProfileUpdateForm, self).__init__(instance=instance, *args, **kwargs)
        self.fields.update(fields_for_model(User, _fields))

    class Meta(object):
        model = Profile

        fields = (
            'sex',
            'address_line1',
            'address_line2',
            'city',
            'state',
            'postal',
            'dob',
            'phone',
            'cell',
            'profile_image',
        )

        widgets = {
            'state': CountrySelectWidget(),
            'dob': forms.SelectDateWidget(
                years=list(reversed(range(1901, 2002))),
                empty_label=(_("Year"), _("Month"), _("Day")),
                attrs=({'style': 'width: 32%; display: inline-block;'})),
            'profile_image': forms.FileInput(),
            'sex': forms.RadioSelect(),
        }

    def save(self, *args, **kwargs):
        u = self.instance.user
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.save()
        profile = super(ProfileUpdateForm, self).save(*args, **kwargs)
        return profile

girls_proj/facemash/forms.py
from django import forms

from .models import Facemash


class FaceForm(forms.Form):
    winner = forms.IntegerField()
    loser = forms.IntegerField()

    def clean_winner(self):
        winner = self.cleaned_data['winner']
        try:
            return Facemash.objects.get(id=winner)
        except Facemash.DoesNotExist:
            raise forms.ValidationError('invalid form')

    def clean_loser(self):
        loser = self.cleaned_data['loser']
        try:
            return Facemash.objects.get(id=loser)
        except Facemash.DoesNotExist:
            raise forms.ValidationError('invalid form')


class FacemashUpdateForm(forms.ModelForm):

    class Meta(object):
        model = Facemash

        fields = (
            'photo',
        )

        widgets = {
            'photo': forms.FileInput(),
        }

girls_proj/accounts/views.py
from django.http import Http404
from django.conf import settings
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext as _


from braces.views import LoginRequiredMixin

from .models import Profile
from .forms import ProfileUpdateForm


class ProfileDetailView(LoginRequiredMixin, DetailView):
    queryset = Profile.objects.select_related('user', 'user__facemash')
    template_name = 'accounts/profile.html'

    def get_object(self):
        try:
            return self.get_queryset().get(slug=self.kwargs['slug'])
        except Profile.DoesNotExist:
            raise Http404


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'accounts/profile_update.html'
    form_class = ProfileUpdateForm

    def get_object(self):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self):
        messages.success(self.request, _('Profile updated successfully'))
        return reverse_lazy('accounts:profile_detail', kwargs={'slug': self.request.user.profile.slug})


class ProfileRedirectView(RedirectView):

    permanent = False
    query_string = True
    pattern_name = 'accounts:profile_detail'

    def get_redirect_url(self, *args, **kwargs):
        kwargs.update({'slug': self.request.user.profile.slug})
        return super(ProfileRedirectView, self).get_redirect_url(*args, **kwargs)

girls_proj/facemash/views.py
import json
import random

from django.http import Http404
from django.contrib import messages
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext as _
from django.views.generic.detail import DetailView
from django.template.loader import render_to_string
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import FormView, UpdateView
from django.http import HttpResponseRedirect, Http404, HttpResponse

from braces.views import LoginRequiredMixin

from .models import Facemash
from .utils import calculate_rating
from .forms import FaceForm, FacemashUpdateForm
from .helpers import cache_hits, get_top_girls


class PlayView(FormView):
    template_name = 'facemash/facemash.html'
    form_class = FaceForm
    success_url = reverse_lazy("facemash:play")

    def form_valid(self, form):
        if self.request.is_ajax():
            winner = form.cleaned_data['winner']
            loser = form.cleaned_data['loser']
            calculate_rating(winner, loser)
            data = render_to_string("facemash/ajax.html", self.get_context_data())
            return HttpResponse(data)
        return super(PlayView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PlayView, self).get_context_data(**kwargs)
# ///////////////////////////////////////////////////////////////
        # contestants = Facemash.objects.all()
        # contestant_1 = random.choice(contestants)
        # contestant_2 = random.choice(contestants)
        # # A while loop to ensure that the contestants aren't same.
        # while contestant_1 == contestant_2:
        #     contestant_2 = random.choice(contestants)
# //////////////////////////////////////////////////////////////////
        # contestants = Facemash.objects.order_by('?')[:2]
        # contestant_1 = contestants.first()
        # contestant_2 = contestants.last()
        # # A while loop to ensure that the contestants aren't same.
        # while contestant_1 == contestant_2:
        #     contestant_2 = random.choice(contestants)
# //////////////////////////////////////////////////////
        last = Facemash.objects.count() - 1
        index1 = random.randint(0, last)
        # Here's one simple way to keep even distribution for
        # index2 while still gauranteeing not to match index1.
        index2 = random.randint(0, last - 1)
        if index2 == index1: index2 = last
        contestant_1 = Facemash.objects.all()[index1]
        contestant_2 = Facemash.objects.all()[index2]
# ///////////////////////////////////////////
        context['contestant_1'] = contestant_1
        context['contestant_2'] = contestant_2
        return context


class RatingsListView(ListView):
    template_name = 'facemash/ratings_page.html'

    def get_context_data(self, **kwargs):
        context = super(RatingsListView, self).get_context_data(**kwargs)
        context['sort_filter'] = self.get_sorting_filter()
        return context

    def order_queryset(self, qs):
        sort_filter = self.get_sorting_filter()
        if sort_filter == 'ratings':
            qs = qs.order_by('-ratings')[:100]
        elif sort_filter == 'views':
            qs = qs.filter(id__in=get_top_girls())
        else:
            qs = qs.order_by('-ratings')[:100]
        return qs

    def get_sorting_filter(self):
        if 'sort_by' in self.request.GET:
            return self.request.GET.get('sort_by')
        else:
            return None

    def get_queryset(self):
        qs = Facemash.objects.active()

        qs = self.order_queryset(qs)
        return qs


class GirlDetailView(DetailView):
    model = Facemash
    template_name = 'facemash/girl_detail.html'

    def get_object(self):
        try:
            girl_object = self.get_queryset().get(slug=self.kwargs['slug'])
            if girl_object.is_active:
                cache_hits(girl_object.id, self.request)
            return girl_object
        except Facemash.DoesNotExist:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(GirlDetailView, self).get_context_data(**kwargs)
        context['avarage'] = Facemash.objects.count_average()
        return context


class FacemashUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'facemash/facemash_update.html'
    form_class = FacemashUpdateForm

    def get_object(self):
        return self.request.user.facemash

    def get_success_url(self):
        messages.success(self.request, _('Фото оновлено вдало'))
        return reverse_lazy('accounts:profile_detail', kwargs={'slug': self.request.user.profile.slug})

girls_proj/landing/views.py
from django.utils.translation import ugettext as _
from django.views.generic import ListView, TemplateView

from watson import search as watson


class SearchListView(ListView):
    template_name = 'landing/search_page.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        context['q'] = self.get_search_query()
        return context

    def get_search_query(self):
        if 'q' in self.request.GET:
            return self.request.GET.get('q')
        else:
            return None

    def get_queryset(self):
        search_query = self.get_search_query()
        if search_query is not None:
            search_results = watson.search(search_query)
            return search_results
        return []


class AboutPage(TemplateView):
    template_name = 'landing/about.html'

girls_proj/templates/accounts/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    {{ block.super }} | {{ profile.user.get_full_name }}
{% endblock %}




{% block body %}

<div class="row m-b-lg m-t-lg">

    <div class="btn-group pull-right"><a class="btn btn-w-m btn-success" href="{% url 'accounts:profile_update' request.user.profile.slug %}" type="button">{% trans "Редагувати" %} <span class=""><i class="fa fa-cog"></i></span></a></div>

    <div class="col-md-2 col-sm-offset-2">
        <div class="">
            <img src="{{ profile.get_avatar_sm }}" class="img-circle circle-border m-b-md" alt="profile">
        </div>
    </div>

    <div class="col-md-6">

        <div class="ibox-content">
            <div class="">
                <div>
                    <h2 class="no-margins">
                        {{ profile.user.get_full_name }}
                    </h2>
                    <br>
                <address>
                    <strong>{{ profile.user.username|default:"-" }}</strong>
                    <br> {{ profile.address_line1|default:"-" }}
                    <br> {{ profile.address_line2|default:"-" }}
                    <br> {{ profile.city|default:"-" }}
                    <br> {{ profile.state.name|default:"-" }}
                    <br> {{ profile.postal|default:"-" }}
                    <br> {{ profile.dob|default:"-" }}
                    <br>
                    <abbr title="Phone">{% trans "Тел" %}:</abbr> {{ profile.phone|default:"-" }}
                    <br>
                    <abbr title="Cell Phone">{% trans "Мобільний" %}:</abbr> {{ profile.cell|default:"-" }}
                </address>
                </div>
            </div>
        </div>
    </div>

</div>


{% if profile.user.facemash %}
<div class="row m-b-lg m-t-lg">

    <div class="btn-group pull-right"><a class="btn btn-w-m btn-success" href="{% url 'facemash:update' %}" type="button">{% trans "Редагувати Фото на сайті" %} <span class=""><i class="fa fa-cog"></i></span></a></div>


    <div class="col-md-2 col-sm-offset-2">
        <div class="">
            <img src="{{ profile.user.facemash.photo_sm.url }}" class="img-circle circle-border m-b-md" alt="profile">
        </div>
    </div>


</div>
{% endif %}

{% endblock body %}

girls_proj/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load countries %}


{% block title %}
    {{ block.super }} | {{ profile.user.get_full_name }}
{% endblock %}



{% block body %}

<form method="POST" enctype="multipart/form-data" action="">{% csrf_token %}

    <div class="row m-b-lg m-t-lg">
        <div class="col-sm-2 col-md-3 col-md-offset-1 col-lg-2 col-lg-offset-2">
            <div class="form-group">
                <img alt="" id="image_avatar" class="img-thumbnail" src="{{ profile.get_avatar_sm }}">
                <span style="display:none">{{ form.profile_image }}</span>
            </div>
            <a id="browse" class="btn btn-block btn-warning fa fa-upload fa-lg"> {% trans 'UPLOAD' %}</a>
        </div>



        <div class="col-sm-10 col-md-8 col-lg-6 card-box">
            <div class="form-group">
                <span>{% trans 'Юзернейм' %}</span>
                <input type="text" class="form-control" id="id_username" maxlength="30" name="username" disabled placeholder="username" spellcheck="false" value="{{ profile.user.username|default_if_none:"" }}">
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <span>{% trans 'Ім’я' %}</span>
                    {% render_field form.first_name class+="form-control" placeholder=form.first_name.label %}
                </div>

                <div class="form-group col-sm-6">
                    <span>{% trans 'Прізвище' %}</span>
                    {% render_field form.last_name class+="form-control" placeholder=form.last_name.label %}
                </div>
            </div>

                
            <div class="form-group">
                <label for="id_sex_0"><input {% if profile.sex == 1 %}checked="checked"{% endif %} id="id_sex_0" name="sex" type="radio" value="1"> {% trans 'Чоловік' %}</label>
                <label for="id_sex_1"><input {% if profile.sex == 0 %}checked="checked"{% endif %} id="id_sex_1" name="sex" type="radio" value="0"> {% trans 'Жінка' %}</label>
            </div>

            <div class="form-group">
                {{ form.birthday }}
            </div>


            <div class="form-group">
                {{ form.country }}
            </div>

            <div class="form-group">
                {% render_field form.address_line1 class+="form-control" placeholder=form.address_line1.label %}
            </div>

            <div class="form-group">
                {% render_field form.address_line2 class+="form-control" placeholder=form.address_line2.label %}
            </div>

            <div class="form-group">
                {% render_field form.phone class+="form-control" placeholder=form.phone.label %}
            </div>

            <div class="form-group">
                {% render_field form.cell class+="form-control" placeholder=form.cell.label %}
            </div>

            <div class="form-group">
                {% render_field form.city class+="form-control" placeholder=form.city.label %}
            </div>

            <div class="form-group">
                {% render_field form.state class+="form-control" placeholder=form.state.label %}
            </div>

            <div class="form-group">
                {% render_field form.postal class+="form-control" placeholder=form.postal.label %}
            </div>

            <div class="form-group">
                {% render_field form.dob class+="form-control" placeholder=form.dob.label %}
            </div>

            <div class="form-group">
                <button class="btn btn-success">{% trans 'ЗБЕРЕГТИ' %}</button>
                <a href="{{ request.user.profile.get_absolute_url }}" class="btn btn-warning"> <span class="fa fa-arrow-left"></span>{% trans 'НАЗАД' %}</a>
            </div>
        </div>

    </div>

</form>

{% endblock body %}



{% block js %}
{{ block.super }}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <script type="text/javascript">
                toastr.warning("{{ error|escape }}")
            </script>
        {% endfor %}
    {% endfor %}
{% endif %}

<script type="text/javascript">
$('#browse').click(function(){
    $(this).parent().find('input').click();
});


document.getElementById("id_profile_image").onchange = function () {
    var reader = new FileReader();
    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image_avatar").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};

</script>
{% endblock js %}